---
kind: pipeline
type: kubernetes
name: sync

node_selector:
  kubernetes.io/arch: amd64

steps:
- name: github
  image: docker.io/appleboy/drone-git-push:latest
  resources:
    limits:
      cpu: 150
      memory: 150M
  settings:
    branch: master
    remote: ssh://git@github.com/fh-trier/linux_ws2122_ansible.git
    force: true
    ssh_key:
      from_secret: ssh_key

- name: email-notification
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 150
      memory: 150M
  when:
    status:
    - changed
    - failure

trigger:
  event:
  - push
  repo:
  - fh-trier/linux_ws2122_ansible
